Make sure both the source locator and the error listener are set in the XPath Compiler and XPath parser, and the XPath object itself. This required passing the error listener to the XPath object, which had a ripple effect on several functions, including the constructor for StylesheetRoot.
This was sparked by BugId 4402417 which Krishna.Meduri@eng.sun.com
submitted to me privately, but may not be the same thing, since
he was getting a NoSuchMethodError, and I don't
have the stylesheet to replicate the bug.

This fixes an error where a null pointer
exception was being thrown if an unknown
function was found.


git-svn-id: https://svn.apache.org/repos/asf/xalan/java/trunk@334201 13f79535-47bb-0310-9956-ffa450edef68