Use JAXP1.1 to get  the XMLReader - there are 5 files where a new XMLReader is created, and now we use SAXParserFactory to get it.
We do check for NoSuchMethodError - that means the code will work even
if you have an old JAXP1.0 parser ( assuming you have the old parser
at the beginning of CLASSPATH, same for JAXP1.0 - since xalan
includes the latest ). Probably that will disapear when no longer needed.

I tested with crimson, xerces ( latest - JAXP1.1 ), xerces ( old - JAXP1.0),
it seems to work fine.

Also, in StylesheetHandler, add an extra check for NPE - during debug
it happened to have an unchecked null ( and it can't hurt to check )


git-svn-id: https://svn.eu.apache.org/repos/asf/xalan/java/trunk@333786 13f79535-47bb-0310-9956-ffa450edef68